### PR TITLE
Reconnect to relay after connection interruption

### LINKED ISSUE #95: auto-reconnect to webhook relay
Sometimes I get a connection error from the CLI:

```
Failed to connect to Webhook Relay:
dial tcp: lookup [api.relay.svix.com](http://api.relay.svix.com/) on [::1]:53: read udp [::1]:53254->[::1]:53: read: connection refused
```

Ideally, it gracefully reconnects and I'm right back to receiving webhooks.

Right now, it crashes and I have to manually restart it.

### PR DESCRIPTION
**Pull request by svix-andor**
Transient network errors can cause the CLI to disconnect from the relay server. In this case we should try to reconnect with a gentle backoff. Fixes #95

### CODE REVIEW

**Review by tasn — APPROVED** [review]
Have you tried it and made sure it works with e.g. DNS connection reset by peer errors like the ticket?

File: relay/relay.go [hunk 1]
```diff
@@ -5,6 +5,7 @@ import (
 	"context"
```
Comment (tasn) [inline relay/relay.go:5]: Copy of my comment, as it's easier to discuss here:
> Have you tried it and made sure it works with e.g. DNS connection reset by peer errors like the ticket?

Comment (svix-andor) [reply relay/relay.go:5]: It should work for any error related to establishment of the connection because I wrapped the entire `c.connect()` setup call. I didn't try specifically with DNS timeouts/connection refused (tried disconnecting local network, overriding API name with something incorrect) but it should work all the same.
